version: "3.2"

services:
  db:
    image: postgres:15rc2-alpine3.16
    restart: always
    volumes:
      - ./bin/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: spending_bot
